name: PROD (Rex) build
on:
  push:
    branches:
      - prod
jobs:
  build:
    uses: KeenMate/gha-shared/.github/workflows/deploy-docker-image.yml@master
    secrets: inherit
    with:
      image-name: svelte-fluentui-docs
      image-tag: prod
      deployment-host: web-03.km8.vm
      deployment-dir: svelte-fluentui-docs
